FROM bitwalker/alpine-elixir:1.5 as build

EXPOSE 4200

COPY config ./config
COPY ui/dist ./ui/dist
COPY certs ./certs
COPY mix.exs .
COPY mix.lock .
COPY _build ./_build

#RUN export MIX_ENV=dev && \
#    rm -Rf _build
#RUN mix compile
RUN apk update
RUN apk add --no-cache openssh

ENTRYPOINT ["/bin/bash"]


