FROM bitwalker/alpine-elixir-phoenix

ARG VERSION=0.1.1

RUN apk upgrade --no-cache && \
    apk add --no-cache bash openssl
    # we need bash and openssl for Phoenix

EXPOSE 4000

ENV PORT=4000 \
    MIX_ENV=prod \
    REPLACE_OS_VARS=true \
    SHELL=/bin/bash

WORKDIR /app

COPY ./_build/prod/rel/exred/releases/${VERSION}/exred.tar.gz .

RUN tar zxf exred.tar.gz && rm exred.tar.gz

RUN chown -R root ./releases

USER root

CMD ["/app/bin/exred", "foreground"]
