FROM resin/rpi-raspbian:stretch

WORKDIR /elixir

RUN set -xe \
  && apt-get update \
  && apt-get install apt-transport-https \
  && echo "deb https://packages.erlang-solutions.com/debian stretch contrib" | tee /etc/apt/sources.list.d/erlang-solutions.list \
  && curl -fSl -O https://packages.erlang-solutions.com/debian/erlang_solutions.asc \
  && apt-key add erlang_solutions.asc \
  && apt-get update \
  && apt-get install elixir \
  && apt-get install erlang-dev erlang-parsetools \
  && apt-get install git openssh-client build-essential

WORKDIR /src

RUN  mix local.hex --force \
  && mix local.rebar --force

#
# add camera support (only works if container is run with --device=/dev/vchiq or --privileged)
#
RUN apt-get -y install libraspberrypi-bin \
 && usermod -a -G video root

CMD modprobe bcm2835-v4l2

#RUN apt-get install -y \
# && postgresql-client \
# && apt-get clean \
# && rm -rf /var/lib/apt/lists/*

