version: "3"
services:
    exred_db:
        image: exred_db:latest
        volumes:
            - ~/exred_postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - exrednet
        environment:
            POSTGRES_USER: exred_user
            POSTGRES_PASSWORD: hello
            POSTGRES_DB: exred_ui_dev
    exred:
        image: exred:latest
        depends_on:
          - "exred_db"
        volumes:
          - ~/exred_data:/var/exred_data
        ports:
            - "4000:4000"
        networks:
            - exrednet
        environment:
            EXRED_DB_HOSTNAME: exred_db
            EXRED_DB_PORT: 5432
            EXRED_DB_NAME: exred_ui_dev
            EXRED_DB_USERNAME: exred_user
            EXRED_DB_PASSWORD: hello
        command: ["/usr/local/bin/wait-for-it.sh", "exred_db:5432", "-t", "30", "-s", "--", "/app/bin/exred", "foreground"]
networks:
    exrednet:
