# Build container
#################################
FROM elixir:1.5 as builder

WORKDIR /exred

ENV MIX_ENV=prod

COPY mix.exs mix.lock ./
COPY config config
COPY apps apps
COPY ui/dist ui/dist
COPY rel rel

RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix do deps.get, deps.compile

RUN MIX_ENV=prod mix phx.digest
RUN MIX_ENV=prod mix compile
RUN mix release --env=prod --verbose


# Final image
#################################
FROM elixir:1.5

ARG VERSION=0.1.5

EXPOSE 4000

ENV MIX_ENV=prod \
    REPLACE_OS_VARS=true \
    SHELL=/bin/bash

COPY docker/assets/wait-for-it.sh /usr/local/bin/
COPY docker/assets/wait-for-postgres.sh /usr/local/bin/

RUN apt-get update && \ 
    apt-get install -y \
    postgresql-client && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY --from=builder /exred/_build/prod/rel/exred/releases/${VERSION}/exred.tar.gz .
RUN tar zxf exred.tar.gz && rm exred.tar.gz
RUN chown -R root ./releases

# truncate conf file, configuration will be passed in through environment variables (see conf. schemas)
RUN echo "" > ./releases/${VERSION}/exred.conf


USER root
CMD ["/app/bin/exred", "foreground"]
